/**
 * Color conversion utilities for DaisyUI theming.
 * DaisyUI v5 uses oklch color format for all theme colors.
 * The conversion functions were largely generated by Opus 4.5
 */

/**
 * Parse a hex color string to RGB values (0-255)
 */
function parseHex(hex: string): { r: number; g: number; b: number } | null {
    // Remove # prefix if present
    hex = hex.replace(/^#/, '');

    let r: number, g: number, b: number;

    if (hex.length === 3) {
        // Short form #rgb
        r = parseInt(hex[0] + hex[0], 16);
        g = parseInt(hex[1] + hex[1], 16);
        b = parseInt(hex[2] + hex[2], 16);
    } else if (hex.length === 6 || hex.length === 8) {
        // Full form #rrggbb or #rrggbbaa (ignore alpha)
        r = parseInt(hex.slice(0, 2), 16);
        g = parseInt(hex.slice(2, 4), 16);
        b = parseInt(hex.slice(4, 6), 16);
    } else {
        return null;
    }

    if (isNaN(r) || isNaN(g) || isNaN(b)) {
        return null;
    }

    return { r, g, b };
}

/**
 * Parse an rgb() or rgba() color string to RGB values (0-255)
 */
function parseRgb(
    rgb: string,
): { r: number; g: number; b: number; a?: number } | null {
    // Match rgb(r, g, b) or rgba(r, g, b, a) or modern rgb(r g b) / rgb(r g b / a)
    const match = rgb.match(
        /rgba?\(\s*(\d+(?:\.\d+)?%?)\s*[,\s]\s*(\d+(?:\.\d+)?%?)\s*[,\s]\s*(\d+(?:\.\d+)?%?)(?:\s*[,/]\s*(\d*\.?\d+%?))?\s*\)/i,
    );

    if (!match) return null;

    const parseValue = (val: string): number => {
        if (val.endsWith('%')) {
            return (parseFloat(val) / 100) * 255;
        }
        return parseFloat(val);
    };

    const r = parseValue(match[1]);
    const g = parseValue(match[2]);
    const b = parseValue(match[3]);

    if (isNaN(r) || isNaN(g) || isNaN(b)) {
        return null;
    }

    return { r, g, b };
}

/**
 * Convert sRGB to linear RGB
 */
function srgbToLinear(c: number): number {
    const v = c / 255;
    return v <= 0.04045 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
}

/**
 * Convert linear RGB to XYZ (D65 illuminant)
 */
function linearRgbToXyz(
    r: number,
    g: number,
    b: number,
): { x: number; y: number; z: number } {
    return {
        x: 0.4124564 * r + 0.3575761 * g + 0.1804375 * b,
        y: 0.2126729 * r + 0.7151522 * g + 0.072175 * b,
        z: 0.0193339 * r + 0.119192 * g + 0.9503041 * b,
    };
}

/**
 * Convert XYZ to OKLAB
 * Using the standard OKLAB transformation matrices
 */
function xyzToOklab(
    x: number,
    y: number,
    z: number,
): { L: number; a: number; b: number } {
    // XYZ to LMS (using OKLAB's M1 matrix)
    const l = 0.8189330101 * x + 0.3618667424 * y - 0.1288597137 * z;
    const m = 0.0329845436 * x + 0.9293118715 * y + 0.0361456387 * z;
    const s = 0.0482003018 * x + 0.2643662691 * y + 0.633851707 * z;

    // Cube root
    const l_ = Math.cbrt(l);
    const m_ = Math.cbrt(m);
    const s_ = Math.cbrt(s);

    // LMS to OKLAB (using OKLAB's M2 matrix)
    return {
        L: 0.2104542553 * l_ + 0.793617785 * m_ - 0.0040720468 * s_,
        a: 1.9779984951 * l_ - 2.428592205 * m_ + 0.4505937099 * s_,
        b: 0.0259040371 * l_ + 0.7827717662 * m_ - 0.808675766 * s_,
    };
}

/**
 * Convert OKLAB to OKLCH
 */
function oklabToOklch(
    L: number,
    a: number,
    b: number,
): { L: number; C: number; h: number } {
    const C = Math.sqrt(a * a + b * b);
    let h = (Math.atan2(b, a) * 180) / Math.PI;
    if (h < 0) h += 360;

    return { L, C, h };
}

/**
 * Convert RGB (0-255) to OKLCH
 */
function rgbToOklch(
    r: number,
    g: number,
    b: number,
): { L: number; C: number; h: number } {
    // sRGB to linear RGB
    const lr = srgbToLinear(r);
    const lg = srgbToLinear(g);
    const lb = srgbToLinear(b);

    // Linear RGB to XYZ
    const { x, y, z } = linearRgbToXyz(lr, lg, lb);

    // XYZ to OKLAB
    const { L, a, b: labB } = xyzToOklab(x, y, z);

    // OKLAB to OKLCH
    return oklabToOklch(L, a, labB);
}

/**
 * Format OKLCH values as a CSS oklch() string
 * @param L - Lightness (0-1)
 * @param C - Chroma (typically 0-0.4)
 * @param h - Hue (0-360)
 */
function formatOklch(L: number, C: number, h: number): string {
    // L as percentage, C as decimal, h in degrees
    const lPercent = (L * 100).toFixed(2);
    const cValue = C.toFixed(4);
    const hValue = C < 0.0001 ? 0 : h.toFixed(2); // For achromatic colors, hue is meaningless

    return `oklch(${lPercent}% ${cValue} ${hValue})`;
}

/**
 * Check if a string is already in oklch format
 */
export function isOklch(value: string): boolean {
    return value.trim().toLowerCase().startsWith('oklch(');
}

/**
 * Check if a string is a hex color
 */
export function isHex(value: string): boolean {
    return /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/.test(
        value.trim(),
    );
}

/**
 * Check if a string is an rgb() or rgba() color
 */
export function isRgb(value: string): boolean {
    return /^rgba?\s*\(/i.test(value.trim());
}

/**
 * Convert hex color to oklch format for DaisyUI
 * @param hex - Color in hex format (#rgb, #rrggbb, or #rrggbbaa)
 * @returns oklch string like "oklch(65.00% 0.2000 250.00)"
 */
export function hexToOklch(hex: string): string {
    const rgb = parseHex(hex);
    if (!rgb) {
        console.warn(`Invalid hex color: ${hex}, returning as-is`);
        return hex;
    }

    const { L, C, h } = rgbToOklch(rgb.r, rgb.g, rgb.b);
    return formatOklch(L, C, h);
}

/**
 * Convert rgb() color to oklch format for DaisyUI
 * @param rgb - Color in rgb(r, g, b) or rgba(r, g, b, a) format
 * @returns oklch string like "oklch(65.00% 0.2000 250.00)"
 */
export function rgbToOklchString(rgb: string): string {
    const parsed = parseRgb(rgb);
    if (!parsed) {
        console.warn(`Invalid rgb color: ${rgb}, returning as-is`);
        return rgb;
    }

    const { L, C, h } = rgbToOklch(parsed.r, parsed.g, parsed.b);
    return formatOklch(L, C, h);
}

/**
 * Normalize color input - accepts hex, rgb(), or oklch()
 * Converts hex and rgb to oklch format for DaisyUI compatibility.
 * @param color - Color in any supported format
 * @returns oklch string or original value if already oklch
 */
export function normalizeColor(color: string): string {
    const trimmed = color.trim();

    if (isOklch(trimmed)) {
        return trimmed;
    }

    if (isHex(trimmed)) {
        return hexToOklch(trimmed);
    }

    if (isRgb(trimmed)) {
        return rgbToOklchString(trimmed);
    }

    // Pass through as-is (could be a CSS variable, named color, etc.)
    console.warn(`Unrecognized color format: ${color}, passing through as-is`);
    return color;
}
