/*
 * Build-time notifying-member codegen (build tooling — never published).
 *
 * Derives the list of `ViewerState` members whose changes wake subscribers —
 * the `command` and `observable` entries of `state-inventory.ts`, in inventory
 * order — and writes it to `src/lib/generated/notifyingMembers.ts`.
 *
 * Why generated rather than imported at runtime: importing the inventory pulls
 * its review prose — classifications, mutator lists, and ~72 explanatory notes —
 * into every shipped bundle for the sake of ~49 strings. Why generated rather
 * than checked in: the checked-in copy carried a "edit this list only together
 * with `state-inventory.ts`" instruction that only a test could enforce, so
 * adding one state member meant editing three files and the compiler could not
 * help. The emitted array is byte-for-byte what the hand-maintained one was, so
 * this costs the bundle nothing.
 *
 * Run directly: `node ./scripts/generate-state-members.ts` (Node strips the TS
 * types). Runs automatically before build/check/test/dev, like `gen:icons`.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { STATE_INVENTORY } from '../src/lib/state/state-inventory.ts';

export function notifyingMembers(
    inventory: readonly { member: string; classification: string }[],
): string[] {
    return inventory
        .filter(
            (entry) =>
                entry.classification === 'command' ||
                entry.classification === 'observable',
        )
        .map((entry) => entry.member);
}

export function renderModule(members: readonly string[]): string {
    const entries = members.map((member) => `    '${member}',`).join('\n');
    return `/**
 * GENERATED by scripts/generate-state-members.ts — do not edit.
 *
 * The \`ViewerState\` members whose changes wake subscribers: the \`command\`
 * and \`observable\` entries of the state inventory, in inventory order.
 * \`internal\` and \`query-only\` members never notify (ADR 0008).
 */
export const NOTIFYING_MEMBERS: readonly string[] = [
${entries}
];
`;
}

// CLI entry.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
    const outDir = fileURLToPath(
        new URL('../src/lib/generated', import.meta.url),
    );
    mkdirSync(outDir, { recursive: true });
    const members = notifyingMembers(STATE_INVENTORY);
    writeFileSync(
        `${outDir}/notifyingMembers.ts`,
        renderModule(members),
        'utf8',
    );
    console.log(
        `generate-state-members: wrote ${members.length} notifying member(s) to src/lib/generated/notifyingMembers.ts`,
    );
}
