/**
 * The three faces in their nine files, and the one thing that makes them "the
 * same faces on every surface": the shared shell's stylesheet, the site's head
 * preloads, and the documentation generator's font override all have to name
 * the same files and slice them the same way.
 *
 * Whether the type is *applied* is a browser fact and lives in
 * `tests/type.spec.ts`. What is asserted here is agreement between four files
 * that cannot import from each other — a `.css`, an `.html`, a Jinja partial and
 * a TOML config — and the existence of the bytes all of them point at. That is
 * exactly the failure a browser check cannot see: a face renamed on one surface
 * still renders, in a fallback, and looks nearly right.
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { TOKENS_CSS } from '@triiiceratops/shell/paths';

import { describe, expect, it } from 'vitest';

/** The three faces, each served as a full file and two `unicode-range` slices. */
const FACES = [
    {
        stem: 'SourceSerif4Variable-Roman',
        family: 'Source Serif 4',
        style: 'normal',
    },
    {
        stem: 'SourceSerif4Variable-Italic',
        family: 'Source Serif 4',
        style: 'italic',
    },
    {
        stem: 'SourceCodeVariable-Roman',
        family: 'Source Code Pro',
        style: 'normal',
    },
] as const;

/**
 * The slices, in the order a stylesheet has to declare them.
 *
 * `null` is the full face, and it comes FIRST and carries no `unicode-range`: a
 * browser picks the last declared face that covers a codepoint, so the slices
 * have to follow it to win for what they carry. Reversed, every page downloads
 * the whole face and the split buys nothing — which reads as entirely correct
 * in the stylesheet, hence the ordering assertion below.
 */
const SLICES = [null, 'LatinExt', 'Latin'] as const;

/** Every font file the two surfaces name, in declaration order. */
const FONT_FILES = FACES.flatMap((face) =>
    SLICES.map((slice) => ({
        ...face,
        slice,
        file: `${face.stem}${slice === null ? '' : `-${slice}`}.woff2`,
    })),
);

function read(relative: string): string {
    return readFileSync(
        fileURLToPath(new URL(relative, import.meta.url)),
        'utf8',
    );
}

const TOKENS_CSS_TEXT = readFileSync(TOKENS_CSS, 'utf8');
const APP_HTML = read('../../src/app.html');

/** The body of every `@font-face` rule in a stylesheet, in source order. */
function faceRules(css: string): string[] {
    return [...css.matchAll(/@font-face\s*\{([^}]*)\}/g)].map(
        (match) => match[1],
    );
}

describe('the font files', () => {
    it('are the nine the site serves out of its own static directory', () => {
        for (const { file } of FONT_FILES) {
            const path = fileURLToPath(
                new URL(`../../static/fonts/${file}`, import.meta.url),
            );
            expect(existsSync(path), `${file} is committed`).toBe(true);
        }
    });

    it('are generated by a command anyone can re-run', () => {
        // The slices are committed, so the only thing that makes them
        // trustworthy is that anyone can regenerate them and compare. Named
        // here so a reader who finds a stale slice knows what to run, and so
        // that deleting the script fails a test rather than nothing.
        const script = fileURLToPath(
            new URL('../../../../scripts/subset-fonts.mjs', import.meta.url),
        );
        expect(existsSync(script), 'scripts/subset-fonts.mjs').toBe(true);
        const source = readFileSync(script, 'utf8');
        for (const { stem } of FACES) expect(source).toContain(stem);
        expect(source, 'a mode that verifies the committed slices').toContain(
            '--check',
        );
    });

    it('subset every face, and each slice is smaller than its face', () => {
        // Which files are subsets and which are the originals, asserted as
        // arithmetic. A slice that is not smaller means the subsetter cut
        // nothing — a generation that failed without saying so.
        const size = (file: string) =>
            readFileSync(
                fileURLToPath(
                    new URL(`../../static/fonts/${file}`, import.meta.url),
                ),
            ).length;
        for (const { stem } of FACES) {
            const full = size(`${stem}.woff2`);
            for (const slice of ['Latin', 'LatinExt']) {
                expect(
                    size(`${stem}-${slice}.woff2`),
                    `${stem}-${slice} is a subset of ${stem}`,
                ).toBeLessThan(full);
            }
        }
    });

    it('ship the licence they are redistributed under, slices included', () => {
        const licence = read('../../static/fonts/LICENSE.txt');
        expect(licence).toContain('SIL OPEN FONT LICENSE');
        for (const { stem } of FACES)
            expect(licence).toContain(`${stem}.woff2`);
        // The slices are derived works. The licence has to say so, say where
        // they came from, and say how to reproduce them.
        expect(licence).toContain('-Latin.woff2');
        expect(licence).toContain('-LatinExt.woff2');
        expect(licence).toContain('scripts/subset-fonts.mjs');
    });
});

describe('tokens.css', () => {
    const rules = faceRules(TOKENS_CSS_TEXT);

    it('declares one rule per file, and no others', () => {
        expect(rules).toHaveLength(FONT_FILES.length);
    });

    it.each(FONT_FILES)('declares $family $style from $file', (entry) => {
        const rule = rules.find((candidate) =>
            candidate.includes(`/fonts/${entry.file}'`),
        );
        expect(rule, `a rule sourcing ${entry.file}`).toBeDefined();
        expect(rule).toContain(`font-family: '${entry.family}'`);
        expect(rule).toContain(`font-style: ${entry.style}`);
        // The variable faces are shipped along their whole weight axis, slices
        // included: one rule covers the range rather than a static instance
        // per weight.
        expect(rule).toContain('font-weight: 200 900');
        // A face with no `font-display` blocks text for up to three seconds on
        // the connection this site is scored on.
        expect(rule).toMatch(/font-display: (swap|fallback|optional)/);

        if (entry.slice === null) {
            // The full face answers for everything, so it carries no range.
            expect(
                rule,
                `${entry.file} is the fallback and must not be range-limited`,
            ).not.toContain('unicode-range');
        } else {
            expect(rule, `${entry.file} is a slice`).toContain('unicode-range');
        }
    });

    it('declares each face before its slices', () => {
        /*
         * The mechanism, and the one thing about it that is invisible when
         * wrong. A browser picks the LAST declared face covering a codepoint,
         * so the full file has to come first and the slices after it. Reversed,
         * the full face wins for Latin too and every page downloads 419 KB
         * instead of 192 KB — with a stylesheet that still reads as correct and
         * a site that still renders perfectly.
         */
        for (const { stem } of FACES) {
            const at = (file: string) =>
                rules.findIndex((rule) => rule.includes(`/fonts/${file}'`));
            const full = at(`${stem}.woff2`);
            for (const slice of ['Latin', 'LatinExt']) {
                expect(
                    at(`${stem}-${slice}.woff2`),
                    `${stem}-${slice} must be declared after ${stem}`,
                ).toBeGreaterThan(full);
            }
        }
    });

    it('carries the rightwards arrow in the latin slice', () => {
        /*
         * U+2192 is the site's own addition to Google's `latin` range, which
         * carries U+2191 and U+2193 either side of it and not this one. The
         * rail's outbound links and every next-page link are set with it, so
         * without it one arrow per page fetched the whole 419 KB face — four
         * points of performance, invisible in review. `tests/type.spec.ts`
         * catches it in a browser; this catches it in the range itself.
         */
        for (const rule of rules.filter((candidate) =>
            candidate.includes('-Latin.woff2'),
        )) {
            expect(rule.replace(/\s+/g, ' ')).toContain('U+2192');
        }
    });

    it('names each family ahead of a system fallback in its token', () => {
        const face = /--face:([^;]*);/.exec(TOKENS_CSS_TEXT)?.[1] ?? '';
        const mono = /--mono:([^;]*);/.exec(TOKENS_CSS_TEXT)?.[1] ?? '';
        expect(face.trimStart()).toMatch(/^'Source Serif 4',/);
        expect(face).toContain('serif');
        expect(mono.trimStart()).toMatch(/^'Source Code Pro',/);
        expect(mono).toContain('monospace');
    });
});

describe('app.html', () => {
    /*
     * One file is preloaded globally: the roman's `latin` slice.
     *
     * Ticket 05 preloaded all three faces; ticket 06's measurement overturned
     * that, because preloading the italic and the mono that first paint never
     * uses competed with the roman for the throttled link and cost three
     * points. Ticket 07 narrowed what remains from the full 419 KB roman to its
     * 192 KB `latin` slice, which is all English prose paints. Every half is
     * asserted — the slice is preloaded, and neither the full faces nor the
     * other faces' slices are — so restoring any of it fails here rather than
     * only in the score gate, which is a whole site build away.
     */
    const PRELOADED = 'SourceSerif4Variable-Roman-Latin.woff2';

    it(`preloads ${PRELOADED} as a font`, () => {
        const link = APP_HTML.slice(
            APP_HTML.lastIndexOf('<link', APP_HTML.indexOf(PRELOADED)),
        ).split('/>')[0];
        expect(link, `a preload for ${PRELOADED}`).toContain('rel="preload"');
        expect(link).toContain('as="font"');
        expect(link).toContain('type="font/woff2"');
        // A font is fetched in CORS mode even same-origin: a preload without
        // this is fetched a second time rather than reused.
        expect(link).toContain('crossorigin');
    });

    it.each(FONT_FILES.filter(({ file }) => file !== PRELOADED))(
        'leaves $file to be loaded on demand',
        ({ file }) => {
            expect(
                APP_HTML,
                `${file} must not be preloaded globally — first paint does not use it`,
            ).not.toContain(file);
        },
    );
});

describe('the design-system appendix', () => {
    /*
     * The one route that preloads the italic. Its captions are italic and above
     * the fold, so it is the only route whose first paint legitimately needs
     * that face, and it carries the cost alone rather than putting it in the
     * global head.
     *
     * It preloads the `latin` slice, 164 KB rather than the full 339 KB, and
     * the preload is still worth keeping: measured at 100 with it and 99
     * without. This route used to be granted a performance floor of 98 because
     * its first paint needed both full serif faces; the split retired that, and
     * the special case is gone from `tests/score.spec.ts` along with it.
     */
    const SYSTEM_PAGE = read('../../src/routes/(chrome)/system/+page.svelte');

    it('preloads the italic slice for itself, in its own head', () => {
        const head = SYSTEM_PAGE.slice(
            SYSTEM_PAGE.indexOf('<svelte:head>'),
            SYSTEM_PAGE.indexOf('</svelte:head>'),
        );
        expect(head, 'a <svelte:head> block').not.toBe('');
        expect(head).toContain('rel="preload"');
        expect(head).toContain('SourceSerif4Variable-Italic-Latin.woff2');
        expect(head).toContain('as="font"');
        expect(head).toContain('type="font/woff2"');
        expect(head).toContain('crossorigin');
    });
});

describe('the install block', () => {
    /*
     * The one thing that preloads the mono, and it preloads it wherever it is
     * placed. The install block is the call to action, D36 requires that command
     * to be set in Source Code Pro so it renders identically here and in the
     * documentation, and code above the fold is what makes that face a
     * first-paint dependency of the page carrying it.
     *
     * The preload travels with the block rather than with a route, because the
     * block is placed in a content document: a route that gains one gains
     * the dependency, and a route that loses one loses it, with no second place
     * to remember.
     *
     * It preloads the `latin` slice, 28 KB rather than the full 88 KB. Worth
     * recording alongside it: measured before the split, the preload bought
     * 80 ms of first contentful paint and nothing at all of largest contentful
     * paint, which was the metric the front page was short on — the face's cost
     * was bytes on a throttled link, not late discovery. The split is what fixed
     * that; the preload is kept because it is still 37 ms of first paint for
     * nothing.
     */
    const INSTALL_BLOCK = read('../../src/lib/InstallBlock.svelte');

    it('preloads the mono slice in its own head', () => {
        const head = INSTALL_BLOCK.slice(
            INSTALL_BLOCK.indexOf('<svelte:head>'),
            INSTALL_BLOCK.indexOf('</svelte:head>'),
        );
        expect(head, 'a <svelte:head> block').not.toBe('');
        expect(head).toContain('rel="preload"');
        expect(head).toContain('SourceCodeVariable-Roman-Latin.woff2');
        expect(head).toContain('as="font"');
        expect(head).toContain('type="font/woff2"');
        expect(head).toContain('crossorigin');
    });
});

describe('the component-level preloads', () => {
    /*
     * This file is the record of what preloads what, so it has to be able to say
     * "and no others". A stray preload in a third component is the failure the
     * two blocks above cannot see: each asserts its own source and would stay
     * green while a fourth face went onto some route's critical path, costing
     * that route points in a gate that is a whole site build away.
     */
    const SRC_DIR = fileURLToPath(new URL('../../src', import.meta.url));

    /**
     * Every component that can put a tag in a page's head, keyed by what it is:
     * a route's page component by the path it serves, and everything else by its
     * path within `src`.
     */
    function components(): Map<string, string> {
        const found = new Map<string, string>();
        const walk = (directory: string, prefix: string, inRoutes: boolean) => {
            for (const entry of readdirSync(directory, {
                withFileTypes: true,
            })) {
                const at = `${directory}/${entry.name}`;
                if (entry.isDirectory()) {
                    // A layout group names no path segment of its own: the
                    // marketing routes live under `(chrome)` and serve `/size/`,
                    // not `/(chrome)/size/`.
                    walk(
                        at,
                        inRoutes && /^\(.*\)$/.test(entry.name)
                            ? prefix
                            : `${prefix}${entry.name}/`,
                        inRoutes || entry.name === 'routes',
                    );
                } else if (inRoutes && entry.name === '+page.svelte') {
                    found.set(
                        `/${prefix.replace(/^routes\//, '')}`,
                        readFileSync(at, 'utf8'),
                    );
                } else if (!inRoutes && entry.name.endsWith('.svelte')) {
                    found.set(
                        `src/${prefix}${entry.name}`,
                        readFileSync(at, 'utf8'),
                    );
                }
            }
        };
        walk(SRC_DIR, '', false);
        return found;
    }

    /**
     * The whole of it: what preloads a face, and which file it preloads.
     *
     * Both are `latin` slices. Preloading a FULL face would be putting hundreds
     * of kilobytes on a critical path for glyphs the page does not paint, so the
     * declared set records the slice and the sweep compares file names exactly
     * rather than by face.
     */
    const DECLARED = new Map([
        ['src/lib/InstallBlock.svelte', 'SourceCodeVariable-Roman-Latin.woff2'],
        ['/system/', 'SourceSerif4Variable-Italic-Latin.woff2'],
    ]);

    it('are exactly the two declared here, and are slices', () => {
        const preloading = new Map<string, string[]>();
        for (const [path, source] of components()) {
            const files = FONT_FILES.map(({ file }) => file).filter(
                (file) =>
                    // Longest first: every full face's name is a prefix of its
                    // slices', so a naive match reports both.
                    new RegExp(`href="[^"]*${file}"`).test(source) &&
                    source.includes('rel="preload"'),
            );
            if (files.length > 0) preloading.set(path, files);
        }
        expect(
            Object.fromEntries(preloading),
            'anything preloading a face must be declared here, with its reason',
        ).toEqual(
            Object.fromEntries(
                [...DECLARED].map(([path, file]) => [path, [file]]),
            ),
        );
    });
});
