// Shared helpers for the API snapshot tooling (ticket 21).
//
// The declaration mechanism is a d.ts SNAPSHOT (not api-extractor): starting from
// each package's public entry `.d.ts` files (the `types` targets in its
// `package.json` `exports`), we follow only RELATIVE imports within the package's
// own `dist/` to compute the transitively-reachable public type graph — a
// hand-rolled d.ts rollup. That graph is:
//   - the per-package "public declaration report" snapshot content, and
//   - the exact set the no-`any`-in-public-declarations gate scans.
// Internal modules not reachable from a public entry (e.g. the ~200 paraglide
// message files, private components) are excluded by construction.

import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname, relative } from 'node:path';

/** The `types` targets declared anywhere in a package.json (exports + top-level). */
export function entryDtsFromPackage(pkgDir) {
    const pkg = JSON.parse(
        readFileSync(resolve(pkgDir, 'package.json'), 'utf8'),
    );
    const out = new Set();
    const walk = (v) => {
        if (v && typeof v === 'object') {
            if (typeof v.types === 'string') out.add(v.types);
            for (const k of Object.keys(v)) walk(v[k]);
        }
    };
    walk(pkg.exports ?? {});
    if (typeof pkg.types === 'string') out.add(pkg.types);
    return [...out]
        .map((p) => resolve(pkgDir, p))
        .filter((p) => existsSync(p))
        .sort();
}

/** Resolve a relative import specifier to a concrete `.d.ts` inside dist. */
function resolveDts(fromFile, spec) {
    if (!spec.startsWith('.')) return null;
    const base = resolve(dirname(fromFile), spec);
    const candidates = [
        base,
        base + '.d.ts',
        base.replace(/\.js$/, '.d.ts'),
        resolve(base, 'index.d.ts'),
    ];
    for (const c of candidates) {
        if (c.endsWith('.d.ts') && existsSync(c)) return c;
    }
    return null;
}

const IMPORT_RE = /(?:from|import)\s*\(?\s*['"]([^'"]+)['"]/g;

/**
 * Transitively-reachable public `.d.ts` files for a package, from its export
 * entry points, following only relative in-package imports. Returns absolute
 * paths, sorted for determinism.
 */
export function reachableDts(pkgDir) {
    const entries = entryDtsFromPackage(pkgDir);
    const seen = new Set();
    const stack = [...entries];
    while (stack.length) {
        const file = stack.pop();
        if (seen.has(file)) continue;
        seen.add(file);
        const src = readFileSync(file, 'utf8');
        IMPORT_RE.lastIndex = 0;
        let m;
        while ((m = IMPORT_RE.exec(src))) {
            const r = resolveDts(file, m[1]);
            if (r && !seen.has(r)) stack.push(r);
        }
    }
    return { entries, files: [...seen].sort() };
}

/** Normalize a `.d.ts` body so the snapshot is deterministic across machines. */
function normalizeDts(src) {
    return src
        .replace(/\r\n/g, '\n')
        .replace(/^\/\/#\s*sourceMappingURL=.*$/gm, '')
        .replace(/[ \t]+$/gm, '')
        .replace(/\n{3,}/g, '\n\n')
        .trimEnd();
}

/** Strip block + line comments so a token scan sees only real declarations. */
export function stripComments(src) {
    return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');
}

/**
 * Build the human-reviewable per-package declaration report: a normalized,
 * path-sorted concatenation of every reachable public `.d.ts`, each under a
 * `// ── <relpath> ──` banner.
 */
export function renderDeclarationReport(pkgDir, pkgName) {
    const { entries, files } = reachableDts(pkgDir);
    const rel = (f) => relative(pkgDir, f).replace(/\\/g, '/');
    const lines = [];
    lines.push(`// API declaration report — ${pkgName}`);
    lines.push('//');
    lines.push('// Generated by `pnpm api:report`. Do not edit by hand.');
    lines.push('// A d.ts rollup: every public `.d.ts` reachable from the');
    lines.push('// package export entry points, path-sorted and normalized.');
    lines.push('// Entry points:');
    for (const e of entries) lines.push(`//   - ${rel(e)}`);
    lines.push('');
    for (const f of files) {
        lines.push(`// ${'='.repeat(70)}`);
        lines.push(`// FILE: ${rel(f)}`);
        lines.push(`// ${'='.repeat(70)}`);
        lines.push(normalizeDts(readFileSync(f, 'utf8')));
        lines.push('');
    }
    return lines.join('\n').trimEnd() + '\n';
}

/**
 * Scan a package's reachable public `.d.ts` for the `any` type token, ignoring
 * comments. Returns `{ file (pkg-relative), line }` records.
 */
export function scanPublicAny(pkgDir) {
    const { files } = reachableDts(pkgDir);
    const hits = [];
    for (const f of files) {
        const rel = relative(pkgDir, f).replace(/\\/g, '/');
        const cleaned = stripComments(readFileSync(f, 'utf8'));
        for (const raw of cleaned.split('\n')) {
            const line = raw.trim();
            if (/\bany\b/.test(line)) hits.push({ file: rel, line });
        }
    }
    return hits;
}
